[115191] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[1833] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\n"},
[185313] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Soothing Darkness's Add Flat Modifier effect\n"},
[185438] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[323547] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[196819] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[137619] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Marked for Death's Periodic Dummy effect\n"},
[53] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[3408] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Crippling Poison's Decrease Movement Speed% effect\n"},
[8679] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF000050.0%|r nerf to Wound Poison's Modify Healing Recevied% effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[115192] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Dummy effect\n"},
[185422] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[323560] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[328908] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Scaling Class: -7 effect\n"},
[81297] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[107570] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[204197] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Purge the Wicked's Periodic Damage effect\n"},
[300728] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fancy Footwork's Increase Speed% effect\n"},
[323673] = {["edits"] = {}, ["text"] = "A |cFFFF000033.0%|r nerf to School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Mindgames's Absorb Damage effect\nAffected by |cFFFF00000.0%|r nerf to Mindgames's Absorb Healing effect\n"},
[116014] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Add Percent Modifier effect\n"},
[108853] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[11366] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[31661] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[133] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[122] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[321712] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[342814] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Bonded Hearts's Dummy effect\n"},
[8680] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Healing Recevied% effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[328082] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[255909] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Damage Taken% effect\nAffected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\n"},
[53563] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Light's Beacon's Dummy effect\n"},
[345121] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[275779] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[304971] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[85673] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[31935] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[53600] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[317920] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Concentration Aura's Dummy effect\n"},
[197277] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[115804] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Healing Recevied% effect\n"},
[262115] = {["edits"] = {}, ["text"] = "A |cFFFF000037.5%|r nerf to Periodic Damage effect\n"},
[223819] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Add Percent Modifier effect\n"},
[343721] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[1715] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[50622] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Bladestorm Off-Hand's School Damage effect\n"},
[7384] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[315961] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[12294] = {["edits"] = {}, ["text"] = "A |cFFFF000023.6%|r nerf to School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[35395] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[260798] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[24275] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[184575] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[275773] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[20271] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[224266] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Righteous Verdict's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[341282] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Unfurling Darkness's Dummy effect\n"},
[262161] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[204301] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[319175] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[197835] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000060.0%|r nerf to The Dreadlord's Deceit's Add Percent Modifier effect\n"},
[319190] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[85256] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[255937] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to School Damage effect\nAffected by |cFFFF000046.7%|r nerf to Ashes to Dust's Add Flat Modifier effect\n"},
[121471] = {["edits"] = {}, ["text"] = "A |cFFFF000040.0%|r nerf to Dummy effect\n"},
[1784] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[323559] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[343724] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[11327] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[307871] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[25912] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[126664] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[307865] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spear of Bastion's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Spear of Bastion's Unknown effect\n"},
[227847] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Bladestorm's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[281000] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Execute's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[1464] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[64382] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Shattering Throw's Unknown effect\n"},
[32375] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Mass Dispel's Dispel effect\nAffected by |cFFFF00000.0%|r nerf to Mass Dispel's Dummy effect\n"},
[205448] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Void Bolt's Server Side Script effect\n"},
[194249] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Voidform's Dummy effect\n"},
[317221] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[52174] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[34428] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[267611] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Add Percent Modifier effect\n"},
[257044] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Double Tap's Dummy effect\n"},
[781] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Disengage End's Dummy effect\n"},
[19434] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000070.0%|r nerf to Sentinel's Sight's Add Percent Modifier effect\n"},
[260402] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Dummy effect\n"},
[194594] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000070.0%|r nerf to Sentinel's Sight's Add Percent Modifier effect\n"},
[260242] = {["edits"] = {}, ["text"] = "Affected by |cFFFF0000-10.0%|r nerf to Arcane Shot's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Multi-Shot's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Chimaera Shot's Dummy effect\n"},
[57755] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[205191] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[16827] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[212520] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Defensive Stance's Modify Damage Taken% effect\n"},
[345020] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to School Damage effect\n"},
[61684] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[205202] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[115989] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Unholy Blight's Periodic Damage effect\n"},
[315443] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Abomination Limb's Server Side Script effect\nAffected by |cFFFF00000.0%|r nerf to Abomination Limb's School Damage effect\n"},
[319233] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Unholy Pact's Dummy effect\nAffected by |cFFFF000033.3%|r nerf to Unholy Pact's Modify Total Stat% effect\n"},
[319245] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Unholy Pact's Dummy effect\n"},
[319255] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Modify Total Stat% effect\n"},
[53365] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Modify Total Stat% effect\n"},
[107428] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Rising Sun Kick's School Damage effect\n"},
[113656] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fists of Fury's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Fists of Fury's Stun effect\n"},
[117418] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fists of Fury Visual Target's Dummy effect\n"},
[156910] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Light's Beacon's Dummy effect\n"},
[324631] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Ultimate Form's Mechanic Immunity effect\n"},
[61295] = {["edits"] = {}, ["text"] = "A |cFFFF000015.0%|r nerf to Direct Heal effect\n"},
[52127] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Water Shield's Energize Power% effect\n"},
[259489] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Tip of the Spear's Add Percent Modifier effect\n"},
[465] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Devotion Aura's Dummy effect\n"},
[263854] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[5672] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Healing Stream Totem's Direct Heal effect\n"},
[110959] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Greater Invisibility's Unknown effect\n"},
[44425] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[342245] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Alter Time's Override Action Spell effect\n"},
[30451] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[321507] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Touch of the Magi's Dummy effect\n"},
[5143] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Arcane Missiles's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[113724] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Ring of Frost's Periodic Trigger Spell effect\n"},
[153640] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[287280] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[55090] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Scourge Strike's Dummy effect\n"},
[48707] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Acherus Drapes's Add Percent Modifier effect\n"},
[323385] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Ooz's Frictionless Coating's Dummy effect\n"},
[53385] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[269937] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[326731] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[325983] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Glimmer of Light's Scaling Class: -8 effect\n"},
[152262] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[85222] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[325984] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Glimmer of Light's Scaling Class: -8 effect\n"},
[225311] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[269571] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Zeal's School Damage effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[117952] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Emperor's Capacitor's Add Percent Modifier effect\n"},
[115008] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Chi Torpedo's Increase Speed% effect\n"},
[258920] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Immolation Aura's School Damage effect\n"},
[323639] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to The Hunt's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to The Hunt's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to The Hunt's Unknown effect\nAffected by |cFFFF00000.0%|r nerf to The Hunt's Dummy effect\n"},
[323802] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to The Hunt's Root effect\nAffected by |cFFFF00000.0%|r nerf to The Hunt's Stun effect\n"},
[210152] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Death Sweep's Dummy effect\n"},
[198589] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Blur's Unknown effect\n"},
[201427] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Annihilation's School Damage effect\n"},
[343527] = {["edits"] = {}, ["text"] = "A |cFFFF000024.0%|r nerf to Periodic Damage effect\nAffected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[101546] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spinning Crane Kick's School Damage effect\n"},
[172] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Corruption's Periodic Damage effect\n"},
[196099] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Grimoire of Sacrifice's School Damage effect\n"},
[205385] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Shadow Crash's School Damage effect\n"},
[308491] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Resonating Arrow's School Damage effect\n"},
[187650] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Freezing Trap's Unknown effect\n"},
[329849] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to Absorb Damage effect\n"},
[164812] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Twin Moonfire's Add Percent Modifier effect\n"},
[155722] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[194153] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[78674] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[191037] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[164815] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[292360] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Embrace of Bwonsamdi's Health Leech effect\n"},
[202497] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Energize Power effect\nAffected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[190984] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[24858] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[8936] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\nAffected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[774] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Restoration Affinity's Add Percent Modifier effect\n"},
[330334] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Condemn's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317483] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[155625] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Twin Moonfire's Add Percent Modifier effect\n"},
[106830] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[22568] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[5221] = {["edits"] = {}, ["text"] = "A |cFFFF000030.0%|r nerf to Dummy effect\nAffected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[1822] = {["edits"] = {}, ["text"] = "A |cFFFF000040.0%|r nerf to Dummy effect\nAffected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Rake's Periodic Damage effect\n"},
[1079] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[274838] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[106951] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Berserk's Energize Power effect\n"},
[339142] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Eye of Fearful Symmetry's Energize Power effect\n"},
[158188] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Soothing Darkness's Add Flat Modifier effect\n"},
[337851] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Reign of Ancient Kings's Dummy effect\n"},
[22570] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[202028] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[49376] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Dazed's Decrease Movement Speed% effect\n"},
[12042] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Add Percent Modifier effect\n"},
[274283] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[323558] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[2948] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[257541] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Phoenix Flames's Dummy effect\n"},
[345739] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Grim Codex's Summon effect\n"},
[235314] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[257542] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[108978] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Alter Time's Override Action Spell effect\n"},
[33763] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Dark Titan's Advice's Add Percent Modifier effect\n"},
[48438] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Restoration Affinity's Add Percent Modifier effect\n"},
[325748] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[102351] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Cenarion Ward's Periodic Heal effect\n"},
[345545] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Flayedwing Toxin's Periodic Damage effect\n"},
[236776] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Hi-Explosive Trap's Unknown effect\n"},
[310143] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Flicker's Leap effect\nAffected by |cFFFF00000.0%|r nerf to Horn of the Wild Hunt's Unknown effect\nAffected by |cFFFF00000.0%|r nerf to Wild Hunt's Charge's Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Run Without Tiring's Periodic Heal% effect\nAffected by |cFFFF00000.0%|r nerf to Soulshape's Modify Total Stat% effect\n"},
[328231] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Wild Spirits's Unknown effect\n"},
[340203] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[270335] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Shrapnel Bomb's Unknown effect\n"},
[270323] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Pheromone Bomb's Unknown effect\n"},
[190925] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Harpoon's Unknown effect\n"},
[271045] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Volatile Bomb's Unknown effect\n"},
[305496] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[326059] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Primordial Wave's Dummy effect\n"},
[322109] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000062.5%|r nerf to Hidden Master's Forbidden Touch's Add Percent Modifier effect\n"},
[336872] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Righteous Verdict's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[17364] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Stormstrike's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Stormstrike Off-Hand's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Stormstrike's Dummy effect\n"},
[114051] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Windlash's Weapon Damage% effect\nAffected by |cFFFF00000.0%|r nerf to Ascendance's School Damage effect\n"},
[58875] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spirit Walk's Mechanic Immunity effect\n"},
[115356] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Windstrike's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Windstrike Off-Hand's School Damage effect\n"},
[335903] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Doom Winds's Dummy effect\n"},
[201846] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Stormstrike's Trigger Spell effect\nAffected by |cFFFF00000.0%|r nerf to Windstrike's Trigger Spell effect\n"},
[1449] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[323654] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[332922] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Superior Tactics's Dummy effect\n"},
[188196] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000023.3%|r nerf to Stormkeeper's Add Percent Modifier effect\n"},
[78675] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Solar Beam's Interrupt Cast effect\n"},
[263642] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fracture's School Damage effect\n"},
[204255] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Soul Fragments's Periodic Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Shattered Souls's Dummy effect\n"},
[204021] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Spirit of the Darkness Flame's Add Percent Modifier effect\n"},
[204157] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Throw Glaive's School Damage effect\n"},
[228477] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Soul Cleave's School Damage effect\n"},
[212084] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fel Devastation's School Damage effect\n"},
[207771] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Spirit of the Darkness Flame's Add Percent Modifier effect\n"},
[51505] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Lava Burst's School Damage effect\n"},
[191634] = {["edits"] = {}, ["text"] = "A |cFFFF000023.3%|r nerf to Add Percent Modifier effect\n"},
[292361] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Embrace of Pa'ku's Modify Critical Strike% effect\n"},
[187878] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Crash Lightning's School Damage effect\n"},
[259495] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Wildfire Bomb's Unknown effect\n"},
[259391] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Chakrams's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Chakrams's Unknown effect\n"},
[48045] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Mind Sear's Dummy effect\n"},
[183998] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Direct Heal effect\n"},
[211545] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[263853] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[17253] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[1943] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Rupture's Dummy effect\n"},
[263165] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Void Torrent's Periodic Energize Power effect\n"},
[114052] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Restorative Mists's Direct Heal effect\n"},
[2649] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[186387] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Bursting Shot's Decrease Movement Speed% effect\n"},
[198793] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Vengeful Retreat's Decrease Movement Speed% effect\nAffected by |cFFFF00000.0%|r nerf to Vengeful Retreat's Mechanic Immunity effect\n"},
[178963] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Demonic Appetite's Energize Power effect\n"},
[5938] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[333734] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Darkmoon Deck: Repose On Cooldown's Dummy effect\n"},
[292359] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Embrace of Akunda's Direct Heal effect\n"},
[188550] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Dark Titan's Advice's Add Percent Modifier effect\n"},
[18562] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Restoration Affinity's Add Percent Modifier effect\n"},
[33778] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Dark Titan's Advice's Add Percent Modifier effect\n"},
[325733] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[5176] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[90361] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[264735] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[324724] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Unholy Transfusion's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Unholy Transfusion's Direct Heal effect\nAffected by |cFFFF00000.0%|r nerf to Unholy Nova's Direct Heal effect\n"},
[325203] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Unholy Transfusion's Direct Heal effect\n"},
[186254] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Modify Damage Done% effect\n"},
[90328] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[320035] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[317589] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[192106] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Lightning Shield's School Damage effect\n"},
[6789] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Mortal Coil's Direct Heal% effect\n"},
[1122] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Infernal Awakening's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Summon Infernal's Summon effect\n"},
[257040] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spatial Rift's Unknown effect\n"},
[314791] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Shifting Power's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Fae Tendrils's Root effect\n"},
[325130] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[155158] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Periodic Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[205345] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[328305] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[772] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[325886] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Ancient Aftershock's Unknown effect\n"},
[163201] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Execute's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[326062] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[1714] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Casting Speed effect\n"},
[343355] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Void Bolt's Server Side Script effect\n"},
[8042] = {["edits"] = {}, ["text"] = "A |cFFFF000010.0%|r nerf to School Damage effect\n"},
[196884] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Feral Lunge's Dummy effect\n"},
[320224] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Podtender's Summon effect\n"},
[114255] = {["edits"] = {}, ["text"] = "Affected by |cFFFF0000-15.0%|r nerf to Flash Heal's Direct Heal effect\n"},
[188499] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Blade Dance's Dummy effect\n"},
[185123] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Throw Glaive's School Damage effect\n"},
[346502] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fel Devastation's School Damage effect\n"},
[7268] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[307443] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Radiant Spark Vulnerability's Modify Damage Taken% from Caster's Spells effect\n"},
[328620] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Blessing of the Seasons's Override Action Spell effect\n"},
[351140] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[162794] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Chaos Strike's School Damage effect\n"},
[319836] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[196770] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Remorseless Winter's School Damage effect\n"},
[49020] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Obliterate Off-Hand's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Obliterate's School Damage effect\n"},
[49998] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Dummy effect\nAffected by |cFFFF000060.0%|r nerf to Haemostasis's Add Percent Modifier effect\n"},
[49143] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Frost Strike Off-Hand's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Frost Strike's School Damage effect\n"},
[45470] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Haemostasis's Add Percent Modifier effect\n"},
[66188] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Haemostasis's Add Percent Modifier effect\n"},
[279303] = {["edits"] = {}, ["text"] = "A |cFFFF000066.7%|r nerf to School Damage effect\n"},
[212552] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Wraith Walk's Mechanic Immunity effect\n"},
[261947] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fist of the White Tiger's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Fist of the White Tiger's Energize Power effect\n"},
[244813] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[217694] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[44461] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[108503] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Grimoire of Sacrifice's Proc Trigger Spell effect\n"},
[16979] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Immobilized's Root effect\n"},
[79140] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Vendetta's Restore Power effect\n"},
[703] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Subterfuge's Dummy effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[27576] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[1329] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Mutilate's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\n"},
[2823] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF00000.0%|r nerf to Deadly Poison's Periodic Damage effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[2818] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[154953] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[113780] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[5374] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[167105] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[132157] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Holy Nova's Direct Heal effect\n"},
[188443] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000023.3%|r nerf to Stormkeeper's Add Percent Modifier effect\n"},
[336065] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Lava Surge's Add Percent Modifier effect\n"},
[341163] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Smash's School Damage effect\n"},
[328547] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Serrated Bone Spike's Periodic Damage effect\n"},
[344662] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Shattered Psyche's Scaling Class: -9 effect\n"},
[315584] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Instant Poison's School Damage effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[315585] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[324073] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[344664] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Scaling Class: -9 effect\n"},
[327022] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Kindred Empowerment's School Damage effect\n"},
[345316] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[1543] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Flare's Unknown effect\n"},
[226757] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[328306] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[5761] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Numbing Poison's Modify Casting Speed effect\n"},
[24423] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[1330] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Iron Wire's Add Flat Modifier effect\n"},
[255546] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[319504] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[32645] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[344225] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Consumptive Infusion's Scaling Class: -7 effect\nAffected by |cFFFF00000.0%|r nerf to Consumptive Infusion's Dummy effect\n"},
[188501] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spectral Sight's Invisibility Detection effect\nAffected by |cFFFF00000.0%|r nerf to Spectral Sight's Dummy effect\n"},
[199658] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[1680] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Whirlwind's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199850] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[196941] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Judgment of Light's Direct Heal effect\n"},
[185763] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000030.0%|r nerf to Deadshot's Add Flat Modifier effect\n"},
[193315] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[197834] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[86392] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[33891] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Visual Effect: Tree of Life's Dummy effect\n"},
[116] = {["edits"] = {}, ["text"] = "Affected by |cFFFF0000-100.0%|r nerf to Frostbolt's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[114014] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[190411] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Whirlwind Off-Hand's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Whirlwind's School Damage effect\n"},
[335096] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335097] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Crushing Blow's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[46924] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Bladestorm's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[23881] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[85288] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Raging Blow's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[184367] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Rampage's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[32223] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Crusader Aura's Dummy effect\n"},
[95738] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[96103] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[85384] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199667] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[44949] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199851] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199852] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[184707] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[184709] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[201364] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[201363] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335098] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335100] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[162488] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Steel Trap's Unknown effect\n"},
[344154] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Gluttonous Spike's School Damage effect\n"},
[339376] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Periodic Damage effect\n"},
[349857] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Dreadfire Vessel's Scaling Class: -9 effect\n"},
[345364] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Direct Heal effect\n"},
[64843] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Divine Hymn's Direct Heal effect\n"},
[344732] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to Scaling Class: -9 effect\n"},
[325326] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Ascended Eruption's Direct Heal effect\n"},
[44614] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Flurry's Decrease Movement Speed% effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[44544] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Ice Lance's Server Side Script effect\n"},
[84721] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[228598] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[148022] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[327498] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[228354] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[307046] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Elysian Decree's Dummy effect\n"},
[228597] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[740] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Tranquility's Direct Heal effect\n"},
[229837] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Big Red Rays's Scale% effect\n"},
[51723] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000060.0%|r nerf to The Dreadlord's Deceit's Add Percent Modifier effect\n"},
[197721] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Essence of G'Hanir's Dummy effect\n"},
[260364] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Arcane Pulse's Decrease Movement Speed% effect\n"},
[64901] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Symbol of Hope's Energize Power effect\n"},
[156287] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[324263] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Sulfuric Emission's Dummy effect\n"},
[8676] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[263852] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[106785] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[320137] = {["edits"] = {}, ["text"] = "A |cFFFF000023.3%|r nerf to Add Percent Modifier effect\n"},
[258925] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fel Barrage's School Damage effect\n"},
[102543] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Jungle Stalker's Override Action Spell effect\nAffected by |cFFFF00000.0%|r nerf to Berserk's Energize Power effect\n"},
[191837] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Essence Font's Direct Heal effect\n"},
[274074] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Glacial Contagion's Scaling Class: -8 effect\n"},
[228049] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Guardian of the Forgotten Queen's Summon effect\n"},
[256896] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Scaling Class: -8 effect\n"},
[255647] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Light's Judgment's School Damage effect\n"},
[256893] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to School Damage effect\n"},
[326808] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Satiated's Dummy effect\n"},
[195292] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Blood Plague's Periodic Health Leech effect\n"},
[30151] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Pursuit's School Damage effect\n"},
[30213] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Healing Recevied% effect\n"},
[89766] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Axe Toss's Interrupt Cast effect\n"},
[120] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[205021] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[185565] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[2120] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[274281] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[274282] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[197625] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[325289] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Decimating Bolt's Trigger Missiles effect\nAffected by |cFFFF00000.0%|r nerf to Decimating Bolt's School Damage effect\n"},
[341678] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Parasol Fall's Slow Fall effect\n"},
[2098] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[315341] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Between the Eyes's Add Percent Modifier effect\n"},
[313010] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Recently Failed's Dummy effect\n"},
[331850] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[271881] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[292364] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Embrace of Krag'wa's Unknown effect\n"},
[202147] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Second Wind's Dummy effect\n"},
[324143] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Hateful Fetish's Modify Leech% effect\nAffected by |cFFFF00000.0%|r nerf to Conqueror's Banner's Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Raise Banner's Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Repulsive Pennant's Periodic Trigger Spell effect\nAffected by |cFFFF00000.0%|r nerf to Repulsive Pennant's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[115767] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[6343] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[20243] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[202168] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[46968] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[23922] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[6572] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317349] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Condemn's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[157997] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[153596] = {["edits"] = {}, ["text"] = "A |cFFFF000010.0%|r nerf to School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[334058] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Scaling Class: -9 effect\n"},
[347047] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Putrid Burst's Scaling Class: -9 effect\nAffected by |cFFFF00000.0%|r nerf to Darkmoon Deck: Putrescence On Cooldown's Dummy effect\n"},
[228600] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[257538] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[280735] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Execute Off-Hand's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Execute's School Damage effect\n"},
[280849] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[163558] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[336864] = {["edits"] = {}, ["text"] = "A |cFFFF000070.0%|r nerf to Scaling Class: -9 effect\n"},
[292363] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Embrace of Kimbul's Periodic Damage effect\n"},
[196725] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Refreshing Jade Wind's Direct Heal effect\n"},
[190357] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[197626] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[195181] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Marrowrend's Dummy effect\n"},
[108292] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Primal Fury's Energize Power effect\n"},
[49966] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[328923] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fae Transfusion's Periodic Dummy effect\n"},
[281954] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Forward Thrust's Knock Back effect\n"},
[205472] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[345801] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Soul Fragment's Trigger Missiles effect\n"},
[126389] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Forward Thrust's Knock Back effect\n"},
[197628] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[341277] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[195949] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Path of the Elothir Leaves's Dummy effect\n"},
[152279] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Breath of Sindragosa's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Breath of Sindragosa's Energize Power effect\n"},
[155166] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to School Damage effect\n"},
[53595] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[157122] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[343393] = {["edits"] = {}, ["text"] = "A |cFFFF000040.0%|r nerf to Scaling Class: -9 effect\nAffected by |cFFFF00000.0%|r nerf to Anima Font's Trigger Missiles effect\nAffected by |cFFFF00000.0%|r nerf to Anima Font's Unknown effect\n"},
[54680] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[192226] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Liquid Magma Totem's Dummy effect\n"},
[311648] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Swarming Mist's School Damage effect\n"},
[343672] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Conqueror's Banner's Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Hateful Fetish's Modify Leech% effect\n"},
[231895] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Sanctified Wrath's Unknown effect\n"},
[314867] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Shadow Covenant's Silence effect\n"},
[89792] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Flee's Unknown effect\n"},
[263423] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[330898] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fists of Fury's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Fists of Fury Visual Target's Dummy effect\n"},
[207349] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Summon Gargoyle's Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Dark Arbiter's Dummy effect\n"},
[247456] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spirit Bomb's Direct Heal effect\n"},
[114871] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[203795] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Soul Fragments's Periodic Dummy effect\nAffected by |cFFFF00000.0%|r nerf to Shattered Souls's Dummy effect\n"},
[329548] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to School Damage effect\n"},
[114852] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[202347] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[330325] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Condemn's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Condemn Off-Hand's School Damage effect\n"},
[317488] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317489] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[281210] = {["edits"] = {}, ["text"] = "A |cFFFF000066.7%|r nerf to School Damage effect\n"},
[160060] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[328506] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[328622] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Blessing of the Seasons's Override Action Spell effect\n"},
[328281] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Blessing of the Seasons's Override Action Spell effect\n"},
[328282] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Blessing of the Seasons's Override Action Spell effect\n"},
[345549] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Phylactery's Toll's School Damage effect\n"},
[317485] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Condemn's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Condemn Off-Hand's School Damage effect\n"},
[20707] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Soulstone's Dummy effect\n"},
[331624] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Voracious Haste's Modify Rating effect\nAffected by |cFFFF00000.0%|r nerf to Voracious Lethargy's Scaling Class: -7 effect\nAffected by |cFFFF00000.0%|r nerf to Darkmoon Deck: Voracity On Cooldown's Dummy effect\n"},
[120679] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Dire Beast's Modify All Haste% effect\n"},
[315720] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[5308] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Execute Off-Hand's School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\nAffected by |cFFFF00000.0%|r nerf to Execute's School Damage effect\n"},
[159786] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Molten Hide's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[160124] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[345714] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fists of Fury Visual Target's Dummy effect\n"},
[328204] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[263857] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[343142] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF00000.0%|r nerf to Dreadblades's Energize Power effect\n"},
[118000] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[263840] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[596] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Prayer of Healing's Dummy effect\n"},
[280772] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[263892] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[260643] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[191427] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Metamorphosis's School Immunity effect\n"},
[263869] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[24450] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[54644] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Froststorm Breath's Dummy effect\n"},
[88263] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[344865] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fel Rush's Dummy effect\n"},
[280719] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[282449] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[263858] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[157375] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Eye of the Storm's School Damage effect\n"},
[269279] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000080.0%|r nerf to Resounding Protection's Scaling Class: -8 effect\n"},
[280204] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Ruinous Bolt's School Damage effect\n"},
[311444] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Darkmoon Deck: Indomitable On Cooldown's Dummy effect\n"},
[345548] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to Scaling Class: -9 effect\n"},
[345215] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to School Damage effect\n"},
[51690] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\n"},
[57842] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[57841] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000020.0%|r nerf to Killing Spree's School Damage effect\n"},
[313113] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to Scaling Class: -9 effect\n"},
[344351] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[236282] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[285381] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[132469] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Typhoon's Knock Back effect\n"},
[160067] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[314517] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Void Jaunt's Dummy effect\n"},
[302311] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to School Damage effect\n"},
[302312] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to School Damage effect\n"},
[121253] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Stormstout's Last Gasp's Add Percent Modifier effect\n"},
[322729] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Spinning Crane Kick's School Damage effect\n"},
[116847] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Rushing Jade Wind's School Damage effect\n"},
[205636] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Force of Nature's Summon effect\n"},
[1752] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[135286] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Tooth and Claw's Modify Damage Done% to Caster effect\n"},
[114923] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[114954] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[341541] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[313148] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to Scaling Class: -9 effect\n"},
[157981] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[50433] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[207744] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Spirit of the Darkness Flame's Add Percent Modifier effect\n"},
[273034] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Martyr's Breath's Scaling Class: -8 effect\n"},
[225730] = {["edits"] = {}, ["text"] = "A |cFFFF000075.0%|r nerf to Modify Rating effect\n"},
[316593] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Intimidating Shout's Knock Back effect\n"},
[319952] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Voidform's Add Percent Modifier effect\nAffected by |cFFFF00000.0%|r nerf to Void Eruption's School Damage effect\nAffected by |cFFFF00000.0%|r nerf to Surrender to Madness's Dummy effect\n"},
[280720] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[196937] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[200758] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[215661] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[120360] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Barrage's Dummy effect\n"},
[33089] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Vigilance of the Colossus's Scaling Class: -8 effect\n"},
[49206] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Summon Gargoyle's Dummy effect\n"},
[160065] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[160011] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[327478] = {["edits"] = {}, ["text"] = "Affected by |cFFFF00000.0%|r nerf to Fingers of Frost's Unknown effect\nAffected by |cFFFF00000.0%|r nerf to Ice Lance's Server Side Script effect\n"},
[342232] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
