[115191] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[1833] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\n"},
[185313] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Soothing Darkness's Add Flat Modifier effect\n"},
[185438] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[323547] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[196819] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[137619] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[53] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[8679] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF000050.0%|r nerf to Wound Poison's Modify Healing Recevied% effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[115192] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Dummy effect\n"},
[185422] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[323560] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[328908] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Scaling Class: -7 effect\n"},
[81297] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[107570] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[323673] = {["edits"] = {}, ["text"] = "A |cFFFF000033.0%|r nerf to School Damage effect\n"},
[116014] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Add Percent Modifier effect\n"},
[108853] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[11366] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[31661] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[133] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[122] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[321712] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[8680] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Healing Recevied% effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[328082] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[255909] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Damage Taken% effect\nAffected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\n"},
[345121] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[275779] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[304971] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[85673] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[31935] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[53600] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[197277] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[115804] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Healing Recevied% effect\n"},
[262115] = {["edits"] = {}, ["text"] = "A |cFFFF000037.5%|r nerf to Periodic Damage effect\n"},
[223819] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Add Percent Modifier effect\n"},
[343721] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[1715] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[50622] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[7384] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[315961] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[12294] = {["edits"] = {}, ["text"] = "A |cFFFF000023.6%|r nerf to School Damage effect\nAffected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[35395] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[260798] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[24275] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[184575] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[275773] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[20271] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[224266] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Righteous Verdict's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[262161] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[204301] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[319175] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[197835] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000060.0%|r nerf to The Dreadlord's Deceit's Add Percent Modifier effect\n"},
[319190] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[85256] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[255937] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to School Damage effect\nAffected by |cFFFF000046.7%|r nerf to Ashes to Dust's Add Flat Modifier effect\n"},
[121471] = {["edits"] = {}, ["text"] = "A |cFFFF000040.0%|r nerf to Dummy effect\n"},
[1784] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[323559] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[343724] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[11327] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Flat Modifier effect\n"},
[307871] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[25912] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[126664] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[307865] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[227847] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[281000] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[1464] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[64382] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317221] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[52174] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[34428] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[267611] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Add Percent Modifier effect\n"},
[257044] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Double Tap's Dummy effect\n"},
[19434] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000070.0%|r nerf to Sentinel's Sight's Add Percent Modifier effect\n"},
[260402] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Dummy effect\n"},
[194594] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000070.0%|r nerf to Sentinel's Sight's Add Percent Modifier effect\n"},
[57755] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[205191] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[16827] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[345020] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to School Damage effect\n"},
[61684] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[205202] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[319233] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Unholy Pact's Modify Total Stat% effect\n"},
[319255] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Modify Total Stat% effect\n"},
[53365] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Modify Total Stat% effect\n"},
[61295] = {["edits"] = {}, ["text"] = "A |cFFFF000015.0%|r nerf to Direct Heal effect\n"},
[263854] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[44425] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[30451] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[5143] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[153640] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[287280] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[48707] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Acherus Drapes's Add Percent Modifier effect\n"},
[53385] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[269937] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[326731] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[325983] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Glimmer of Light's Scaling Class: -8 effect\n"},
[152262] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[85222] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[325984] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Glimmer of Light's Scaling Class: -8 effect\n"},
[225311] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\n"},
[269571] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[117952] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Emperor's Capacitor's Add Percent Modifier effect\n"},
[343527] = {["edits"] = {}, ["text"] = "A |cFFFF000024.0%|r nerf to Periodic Damage effect\nAffected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[329849] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to Absorb Damage effect\n"},
[164812] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Twin Moonfire's Add Percent Modifier effect\n"},
[155722] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[194153] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[78674] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[191037] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[164815] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[202497] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Energize Power effect\nAffected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[190984] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[24858] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[8936] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\nAffected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[774] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Restoration Affinity's Add Percent Modifier effect\n"},
[330334] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317483] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[155625] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Twin Moonfire's Add Percent Modifier effect\n"},
[106830] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[22568] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[5221] = {["edits"] = {}, ["text"] = "A |cFFFF000030.0%|r nerf to Dummy effect\nAffected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[1822] = {["edits"] = {}, ["text"] = "A |cFFFF000040.0%|r nerf to Dummy effect\nAffected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[1079] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[274838] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[158188] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Soothing Darkness's Add Flat Modifier effect\n"},
[22570] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[202028] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[12042] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to Add Percent Modifier effect\n"},
[274283] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[323558] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Reverberation's Add Percent Modifier effect\n"},
[2948] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[257541] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[345739] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to School Damage effect\n"},
[235314] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[257542] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[33763] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Dark Titan's Advice's Add Percent Modifier effect\n"},
[48438] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Restoration Affinity's Add Percent Modifier effect\n"},
[325748] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[340203] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[305496] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[322109] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000062.5%|r nerf to Hidden Master's Forbidden Touch's Add Percent Modifier effect\n"},
[336872] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Righteous Verdict's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[1449] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[323654] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[188196] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000023.3%|r nerf to Stormkeeper's Add Percent Modifier effect\n"},
[204021] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Spirit of the Darkness Flame's Add Percent Modifier effect\n"},
[207771] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Spirit of the Darkness Flame's Add Percent Modifier effect\n"},
[191634] = {["edits"] = {}, ["text"] = "A |cFFFF000023.3%|r nerf to Add Percent Modifier effect\n"},
[183998] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Direct Heal effect\n"},
[211545] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[263853] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[17253] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[1943] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[2649] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[5938] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[188550] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Dark Titan's Advice's Add Percent Modifier effect\n"},
[18562] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Restoration Affinity's Add Percent Modifier effect\n"},
[33778] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to The Dark Titan's Advice's Add Percent Modifier effect\n"},
[325733] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[5176] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[90361] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[264735] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[186254] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Modify Damage Done% effect\n"},
[90328] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[320035] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[317589] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[314791] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[325130] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[155158] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Periodic Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[205345] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[328305] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[772] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[325886] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[163201] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[326062] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[1714] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Casting Speed effect\n"},
[8042] = {["edits"] = {}, ["text"] = "A |cFFFF000010.0%|r nerf to School Damage effect\n"},
[7268] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[307443] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[351140] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[319836] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[49998] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Dummy effect\nAffected by |cFFFF000060.0%|r nerf to Haemostasis's Add Percent Modifier effect\n"},
[45470] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Haemostasis's Add Percent Modifier effect\n"},
[66188] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Haemostasis's Add Percent Modifier effect\n"},
[279303] = {["edits"] = {}, ["text"] = "A |cFFFF000066.7%|r nerf to School Damage effect\n"},
[244813] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[217694] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[44461] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[703] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Subterfuge's Dummy effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[27576] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[1329] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\n"},
[2823] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[2818] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[154953] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[113780] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[5374] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[167105] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[188443] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000023.3%|r nerf to Stormkeeper's Add Percent Modifier effect\n"},
[328547] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[344662] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Shattered Psyche's Scaling Class: -9 effect\n"},
[315584] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[315585] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[324073] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[344664] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Scaling Class: -9 effect\n"},
[345316] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[226757] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[328306] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[24423] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[1330] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Iron Wire's Add Flat Modifier effect\n"},
[255546] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[319504] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[32645] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[199658] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[1680] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199850] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[185763] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000030.0%|r nerf to Deadshot's Add Flat Modifier effect\n"},
[193315] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[197834] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[86392] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[116] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[114014] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[190411] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335096] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335097] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[46924] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[23881] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[85288] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[184367] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[95738] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[96103] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[85384] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199667] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[44949] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199851] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[199852] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[184707] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[184709] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[201364] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[201363] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335098] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[335100] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[339376] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to Periodic Damage effect\n"},
[349857] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Dreadfire Vessel's Scaling Class: -9 effect\n"},
[345364] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Direct Heal effect\n"},
[344732] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to Scaling Class: -9 effect\n"},
[44614] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[84721] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[228598] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[148022] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[327498] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[228354] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[228597] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[51723] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000060.0%|r nerf to The Dreadlord's Deceit's Add Percent Modifier effect\n"},
[156287] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[8676] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[263852] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[106785] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[320137] = {["edits"] = {}, ["text"] = "A |cFFFF000023.3%|r nerf to Add Percent Modifier effect\n"},
[256896] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Scaling Class: -8 effect\n"},
[255647] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Light's Judgment's School Damage effect\n"},
[256893] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to School Damage effect\n"},
[30213] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to Modify Healing Recevied% effect\n"},
[120] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[205021] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[185565] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[2120] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[274281] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[274282] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[197625] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[2098] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[315341] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Between the Eyes's Add Percent Modifier effect\n"},
[331850] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[271881] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[324143] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[115767] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[6343] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[20243] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[202168] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[46968] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[23922] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[6572] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317349] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[157997] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[153596] = {["edits"] = {}, ["text"] = "A |cFFFF000010.0%|r nerf to School Damage effect\nAffected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[334058] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to Scaling Class: -9 effect\n"},
[347047] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Putrid Burst's Scaling Class: -9 effect\n"},
[228600] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[257538] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[280735] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[280849] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[163558] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[336864] = {["edits"] = {}, ["text"] = "A |cFFFF000070.0%|r nerf to Scaling Class: -9 effect\n"},
[190357] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[197626] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[49966] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[205472] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[197628] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[341277] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[152279] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Breath of Sindragosa's School Damage effect\n"},
[155166] = {["edits"] = {}, ["text"] = "A |cFFFF000033.3%|r nerf to School Damage effect\n"},
[53595] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[157122] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[343393] = {["edits"] = {}, ["text"] = "A |cFFFF000040.0%|r nerf to Scaling Class: -9 effect\n"},
[54680] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[231895] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Sanctified Wrath's Unknown effect\n"},
[263423] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[114871] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[329548] = {["edits"] = {}, ["text"] = "A |cFFFF000025.0%|r nerf to School Damage effect\n"},
[114852] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[202347] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Balance Druid's Add Percent Modifier effect\n"},
[330325] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317488] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[317489] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[281210] = {["edits"] = {}, ["text"] = "A |cFFFF000066.7%|r nerf to School Damage effect\n"},
[160060] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[328506] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[328281] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[317485] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[315720] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[5308] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[159786] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[160124] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[328204] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[263857] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[343142] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000033.3%|r nerf to Toxic Blade's Modify Damage Taken% from Caster's Spells effect\n"},
[118000] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[263840] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[280772] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[263892] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[260643] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[263869] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[24450] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[54644] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[88263] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\n"},
[280719] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[282449] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[263858] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\nAffected by |cFFFF000050.0%|r nerf to Mortal Wounds's Modify Healing Recevied% effect\n"},
[269279] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000080.0%|r nerf to Resounding Protection's Scaling Class: -8 effect\n"},
[345548] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to Scaling Class: -9 effect\n"},
[345215] = {["edits"] = {}, ["text"] = "A |cFFFF000050.0%|r nerf to School Damage effect\n"},
[51690] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\n"},
[57842] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[57841] = {["edits"] = {}, ["text"] = "A |cFFFF000020.0%|r nerf to School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\nAffected by |cFFFF000020.0%|r nerf to Killing Spree's School Damage effect\n"},
[313113] = {["edits"] = {}, ["text"] = "A |cFFFF000055.0%|r nerf to Scaling Class: -9 effect\n"},
[344351] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[236282] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000037.5%|r nerf to Deep Wounds's Periodic Damage effect\n"},
[285381] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000055.0%|r nerf to Feral Druid's Add Percent Modifier effect\n"},
[160067] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[302311] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to School Damage effect\n"},
[302312] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to School Damage effect\n"},
[121253] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000060.0%|r nerf to Stormstout's Last Gasp's Add Percent Modifier effect\n"},
[1752] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[114923] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[114954] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[341541] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[313148] = {["edits"] = {}, ["text"] = "A |cFFFF000060.0%|r nerf to Scaling Class: -9 effect\n"},
[157981] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
[50433] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[207744] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000066.7%|r nerf to Spirit of the Darkness Flame's Add Percent Modifier effect\n"},
[225730] = {["edits"] = {}, ["text"] = "A |cFFFF000075.0%|r nerf to Modify Rating effect\n"},
[280720] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000020.0%|r nerf to Mastery: Executioner's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[196937] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[200758] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000040.0%|r nerf to Shadow Blades's Dummy effect\nAffected by |cFFFF000050.0%|r nerf to Nightstalker's Add Percent Modifier effect\nAffected by |cFFFF000010.6%|r nerf to Subtlety Rogue's Add Flat Modifier effect\nAffected by |cFFFF000022.2%|r nerf to Assassination Rogue's Add Percent Modifier effect\n"},
[215661] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Divine Purpose's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Wake of Ashes's School Damage effect\nAffected by |cFFFF000050.0%|r nerf to Final Reckoning's Modify Damage Taken% from Caster's Spells effect\n"},
[160065] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[160011] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Aspect of the Beast's Add Percent Modifier effect\n"},
[342232] = {["edits"] = {}, ["text"] = "Affected by |cFFFF000033.3%|r nerf to Arcane Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Rune of Power's Add Percent Modifier effect\nAffected by |cFFFF000025.0%|r nerf to Incanter's Flow's Add Percent Modifier effect\n"},
